apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: example-a-
namespace: "<your-namespace>"
resources:
  - http://github.com/utilitywarehouse/energy-postgres-base//manifests/postgres-with-backup?ref=<update-ref-here>
commonLabels:
  app.kubernetes.io/instance: example-a-postgresql
  app.kubernetes.io/name: example-q-postgresql
secretGenerator:
  - name: postgresql
    envs:
      - secrets/postgres.properties
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: postgresql
    envs:
      - config/postgresql
    literals:
      - host=example-a-postgresql
patches:
  - path: postgres.yaml
