apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: example-a-
namespace: "<your-namespace>"
resources:
  - http://github.com/utilitywarehouse/shared-kustomize-bases//postgresql/manifests/postgres-with-backup?ref=<update-ref-here>
secretGenerator:
  - name: postgresql
    envs:
      - secrets/postgres.properties
    options:
          disableNameSuffixHash: true
patches:
  - path: postgres.yaml
