apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  labels:
    app: postgres-backup
spec:
  schedule: "@daily"
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            injector.tumblr.com/request: vault-init-container-aws
        spec:
          imagePullSecrets:
            - name: dockerhub-key
          serviceAccountName: service-account-name
          containers:
            - name: postgres-backup
              image: registry.uw.systems/energy/postgres-base-backup:latest
              imagePullPolicy: "Always"
              volumeMounts:
                - mountPath: /backup
                  name: postgres-backup-pvc
              env:
                - name: S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: backup
                      key: s3-region
                - name: S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: backup
                      key: s3-bucket
                - name: S3_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      name: backup
                      key: s3-prefix
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: postgresql
                      key: host
                - name: POSTGRES_USER
                  valueFrom:
                    configMapKeyRef:
                      name: postgresql
                      key: user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: user-password
                - name: POSTGRES_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: postgresql
                      key: database
                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: postgresql
                      key: port
          restartPolicy: OnFailure
          volumes:
            - name: postgres-backup-pvc
              persistentVolumeClaim:
                claimName: postgres-backup-pvc
